# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ad.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61\x64.proto\x12\x08Yektanet\")\n\nAd_Request\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07min_cpc\x18\x02 \x01(\x03\"(\n\x08\x41\x64_Reply\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t2I\n\nAdsWithCpc\x12;\n\rget_ad_by_cpc\x12\x14.Yektanet.Ad_Request\x1a\x12.Yektanet.Ad_Reply\"\x00\x42\x0cZ\n/Yektanet/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n/Yektanet/'
  _globals['_AD_REQUEST']._serialized_start=22
  _globals['_AD_REQUEST']._serialized_end=63
  _globals['_AD_REPLY']._serialized_start=65
  _globals['_AD_REPLY']._serialized_end=105
  _globals['_ADSWITHCPC']._serialized_start=107
  _globals['_ADSWITHCPC']._serialized_end=180
# @@protoc_insertion_point(module_scope)
